const data = [
  {
  login: "Acquati",
  id: 15040050,
  node_id: "MDQ6VXNlcjE1MDQwMDUw",
  avatar_url: "https://avatars.githubusercontent.com/u/15040050?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Acquati",
  html_url: "https://github.com/Acquati",
  followers_url: "https://api.github.com/users/Acquati/followers",
  following_url: "https://api.github.com/users/Acquati/following{/other_user}",
  gists_url: "https://api.github.com/users/Acquati/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Acquati/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Acquati/subscriptions",
  organizations_url: "https://api.github.com/users/Acquati/orgs",
  repos_url: "https://api.github.com/users/Acquati/repos",
  events_url: "https://api.github.com/users/Acquati/events{/privacy}",
  received_events_url: "https://api.github.com/users/Acquati/received_events",
  type: "User",
  site_admin: false,
  },
  {
  login: "evandrododo",
  id: 192278,
  node_id: "MDQ6VXNlcjE5MjI3OA==",
  avatar_url: "https://avatars.githubusercontent.com/u/192278?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/evandrododo",
  html_url: "https://github.com/evandrododo",
  followers_url: "https://api.github.com/users/evandrododo/followers",
  following_url: "https://api.github.com/users/evandrododo/following{/other_user}",
  gists_url: "https://api.github.com/users/evandrododo/gists{/gist_id}",
  starred_url: "https://api.github.com/users/evandrododo/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/evandrododo/subscriptions",
  organizations_url: "https://api.github.com/users/evandrododo/orgs",
  repos_url: "https://api.github.com/users/evandrododo/repos",
  events_url: "https://api.github.com/users/evandrododo/events{/privacy}",
  received_events_url: "https://api.github.com/users/evandrododo/received_events",
  type: "User",
  site_admin: false,
  },
  {
  login: "fernandesfernando",
  id: 7903384,
  node_id: "MDQ6VXNlcjc5MDMzODQ=",
  avatar_url: "https://avatars.githubusercontent.com/u/7903384?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/fernandesfernando",
  html_url: "https://github.com/fernandesfernando",
  followers_url: "https://api.github.com/users/fernandesfernando/followers",
  following_url: "https://api.github.com/users/fernandesfernando/following{/other_user}",
  gists_url: "https://api.github.com/users/fernandesfernando/gists{/gist_id}",
  starred_url: "https://api.github.com/users/fernandesfernando/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/fernandesfernando/subscriptions",
  organizations_url: "https://api.github.com/users/fernandesfernando/orgs",
  repos_url: "https://api.github.com/users/fernandesfernando/repos",
  events_url: "https://api.github.com/users/fernandesfernando/events{/privacy}",
  received_events_url: "https://api.github.com/users/fernandesfernando/received_events",
  type: "User",
  site_admin: false,
  },
  {
  login: "kellynvd",
  id: 13313889,
  node_id: "MDQ6VXNlcjEzMzEzODg5",
  avatar_url: "https://avatars.githubusercontent.com/u/13313889?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/kellynvd",
  html_url: "https://github.com/kellynvd",
  followers_url: "https://api.github.com/users/kellynvd/followers",
  following_url: "https://api.github.com/users/kellynvd/following{/other_user}",
  gists_url: "https://api.github.com/users/kellynvd/gists{/gist_id}",
  starred_url: "https://api.github.com/users/kellynvd/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/kellynvd/subscriptions",
  organizations_url: "https://api.github.com/users/kellynvd/orgs",
  repos_url: "https://api.github.com/users/kellynvd/repos",
  events_url: "https://api.github.com/users/kellynvd/events{/privacy}",
  received_events_url: "https://api.github.com/users/kellynvd/received_events",
  type: "User",
  site_admin: false,
  },
  {
  login: "renatoagomes",
  id: 9811888,
  node_id: "MDQ6VXNlcjk4MTE4ODg=",
  avatar_url: "https://avatars.githubusercontent.com/u/9811888?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/renatoagomes",
  html_url: "https://github.com/renatoagomes",
  followers_url: "https://api.github.com/users/renatoagomes/followers",
  following_url: "https://api.github.com/users/renatoagomes/following{/other_user}",
  gists_url: "https://api.github.com/users/renatoagomes/gists{/gist_id}",
  starred_url: "https://api.github.com/users/renatoagomes/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/renatoagomes/subscriptions",
  organizations_url: "https://api.github.com/users/renatoagomes/orgs",
  repos_url: "https://api.github.com/users/renatoagomes/repos",
  events_url: "https://api.github.com/users/renatoagomes/events{/privacy}",
  received_events_url: "https://api.github.com/users/renatoagomes/received_events",
  type: "User",
  site_admin: false,
  },
  {
  login: "thesocialdev",
  id: 6544309,
  node_id: "MDQ6VXNlcjY1NDQzMDk=",
  avatar_url: "https://avatars.githubusercontent.com/u/6544309?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/thesocialdev",
  html_url: "https://github.com/thesocialdev",
  followers_url: "https://api.github.com/users/thesocialdev/followers",
  following_url: "https://api.github.com/users/thesocialdev/following{/other_user}",
  gists_url: "https://api.github.com/users/thesocialdev/gists{/gist_id}",
  starred_url: "https://api.github.com/users/thesocialdev/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/thesocialdev/subscriptions",
  organizations_url: "https://api.github.com/users/thesocialdev/orgs",
  repos_url: "https://api.github.com/users/thesocialdev/repos",
  events_url: "https://api.github.com/users/thesocialdev/events{/privacy}",
  received_events_url: "https://api.github.com/users/thesocialdev/received_events",
  type: "User",
  site_admin: false,
  },
  {
  login: "thiagobraga",
  id: 993684,
  node_id: "MDQ6VXNlcjk5MzY4NA==",
  avatar_url: "https://avatars.githubusercontent.com/u/993684?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/thiagobraga",
  html_url: "https://github.com/thiagobraga",
  followers_url: "https://api.github.com/users/thiagobraga/followers",
  following_url: "https://api.github.com/users/thiagobraga/following{/other_user}",
  gists_url: "https://api.github.com/users/thiagobraga/gists{/gist_id}",
  starred_url: "https://api.github.com/users/thiagobraga/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/thiagobraga/subscriptions",
  organizations_url: "https://api.github.com/users/thiagobraga/orgs",
  repos_url: "https://api.github.com/users/thiagobraga/repos",
  events_url: "https://api.github.com/users/thiagobraga/events{/privacy}",
  received_events_url: "https://api.github.com/users/thiagobraga/received_events",
  type: "User",
  site_admin: false,
  },
  ]

  export default data;